{"name": "使用无效凭据登录", "status": "broken", "statusDetails": {"message": "AttributeError: 'Config' object has no attribute 'get_android_capabilities'", "trace": "self = <test_login.TestLogin object at 0x000002610DC5AD50>, method = <bound method TestLogin.test_invalid_login of <test_login.TestLogin object at 0x000002610DC5AD50>>\n\n    def setup_method(self, method):\n        \"\"\"在每个测试方法开始前执行，启动Appium会话\"\"\"\n>       caps = self.config.get_android_capabilities()\nE       AttributeError: 'Config' object has no attribute 'get_android_capabilities'\n\ntestcases\\base_test.py:20: AttributeError"}, "description": "测试使用无效的用户名和密码登录", "start": 1748431533666, "stop": 1748431533666, "uuid": "b839eaa5-0e92-454d-bacb-47142017ce58", "historyId": "f85285519da8525fb5620425bca75abe", "testCaseId": "f85285519da8525fb5620425bca75abe", "fullName": "testcases.test_login.TestLogin#test_invalid_login", "labels": [{"name": "feature", "value": "登录功能"}, {"name": "story", "value": "异常登录"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-QVK4EQ1"}, {"name": "thread", "value": "28800-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}